orders/urls.py
from django.urls import path

from orders.views import (OrderCreateView,
                          SuccessTemplateView,
                          CanceledTemplateView,
                          OrderListView,
                          OrderDetailView, )

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),

    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),

    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),

]

products/urls.py
from django.urls import path

from products.views import (ProductsListView,
                            ProductDetailView,
                            basket_add, basket_remove,
                            CommentLikeView,
                            CommentLikeAdminView,
                            CommentDeleteAdminView,
                            ProductLikeView)

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('product_details/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),

    path('comment-like/<int:comment_id>', CommentLikeView.as_view(), name='comment_like'),
    path('product-like/<int:product_id>', ProductLikeView.as_view(), name='product_like'),
    path('comment-like/admin/<int:comment_id>', CommentLikeAdminView.as_view(), name='comment_admin'),
    path('comment-delete/admin/<int:comment_id>/', CommentDeleteAdminView.as_view(), name='comment_delete_admin'),

    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
import stripe
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY

class ProductCategory(models.Model):
    id = models.IntegerField(primary_key=True, auto_created=False)  # disable auto increment
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')


class Product(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    id = models.IntegerField(primary_key=True, auto_created=False)  # disable auto increment
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    publish = models.DateTimeField(default=timezone.localtime)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='published')

    objects = models.Manager()
    published = PublishManager()

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ('-publish', '-created')

    def __str__(self):
        return f'Product: {self.name} | Category: {self.category.name}'

    def get_absolute_url(self):
        return reverse_lazy('products:product_details',
                            args=[self.pk, ])

    def likes_count(self):
        return self.likes.count()

    def is_liked_by(self, user):
        return self.likes.filter(user=user).exists()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='usd')
        return stripe_product_price


class ProductLike(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_likes')

    class Meta:
        unique_together = ('product', 'user')


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-updated', '-created')

    def __str__(self):
        return f'Comment by {self.author.username} - {self.body}'

    def likes_count(self):
        return self.likes.count()

    def is_liked_by(self, user):
        return self.likes.filter(user=user).exists()


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='comment_likes')

    class Meta:
        unique_together = ('comment', 'user')


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Basket for {self.user.username} | Product: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        return basket_item


"""
on_delete=models.CASCADE - delete all
on_delete=models.PROTECT - you cannot delete a category until all products belonging to this category have been deleted
on_delete=models.SET_DEFAULT, default='...' - when deleted, the default value will be set
"""

products/forms.py
from django import forms

from products.models import Comment


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={'max_length': 255,
                                                         'class': 'form-control border border-4',
                                                         'placeholder': 'Type your comment here...'}))

    class Meta:
        model = Comment
        fields = ('body',)

products/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.views.generic.base import TemplateView, View
from django.views.generic.list import ListView

from common.views import TitleMixin
from products.forms import CommentForm
from products.models import Product, ProductCategory, Basket, Comment, CommentLike, ProductLike


class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'Store'


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 9
    title = 'Store - Catalog'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()  # Product.objects.all()
        queryset = queryset.order_by('id')

        category_id = self.kwargs.get('category_id')  # None
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()

        context['categories'] = ProductCategory.objects.all()
        return context


class ProductDetailView(TitleMixin, DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    title = 'Store - Product details'
    queryset = Product.published.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)

        context['form'] = CommentForm(initial={'product': self.object})
        context['categories'] = ProductCategory.objects.all()
        return context

    @method_decorator(login_required, name='dispatch')
    def post(self, request, *args, **kwargs):
        post_comment = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = Comment(body=request.POST.get('body'),
                                  author=self.request.user,
                                  product=self.get_object())
            new_comment.save()
            return HttpResponseRedirect(f'{post_comment.get_absolute_url()}')
        return self.render_to_response({'product': post_comment, 'form': form})


class CommentLikeView(LoginRequiredMixin, View):
    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        comment_like, created = CommentLike.objects.get_or_create(comment=comment, user=request.user)
        if not created:
            comment_like.delete()
        return HttpResponseRedirect(f'{comment.product.get_absolute_url()}')


class ProductLikeView(LoginRequiredMixin, View):
    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        product_like, created = ProductLike.objects.get_or_create(product=product, user=request.user)
        if not created:
            product_like.delete()
        return HttpResponseRedirect(reverse_lazy('products:index'))


class CommentLikeAdminView(LoginRequiredMixin, View):
    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)

        if not request.user.is_superuser:
            raise PermissionDenied("You don't have permission to admin comments")

        comment.active = False if comment.active else True
        comment.save()
        return HttpResponseRedirect(f'{comment.product.get_absolute_url()}')


class CommentDeleteAdminView(LoginRequiredMixin, View):
    model = Comment

    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        if not request.user.is_superuser:
            raise PermissionDenied("You don't have permission to admin comments")
        comment.delete()
        return HttpResponseRedirect(f'{comment.product.get_absolute_url()}')


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product_id=product_id, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>

    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
{% include 'nav/nav-top-bar.html' %}


{% block content %} {% endblock %}

{% block footer %} {% endblock %}


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script src="{% static 'vendor/js/get_year.js' %}"></script>


</body>

</html>

products/templates/products/baskets.html
{% load humanize %}
{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Basket
        <span class="badge badge-secondary badge-pill">
            {{ baskets.total_quantity }}
        </span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">
                    {{ basket.product.name }}
                </h5>
                <p class="card-text">
                    {{ basket.product.description }}
                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                   value="{{ basket.quantity|intcomma }}" min="0">
                        </div>
                        <div class="col-lg-4">
                            {{ basket.sum|intcomma }} usdt.
                        </div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket_remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">
                Total
            </p>
            <h4 class="float-right">
                {{ baskets.total_sum|intcomma }} usdt
            </h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
        Checkout
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Basket is empty
    </h4>
{% endif %}

products/templates/products/footer.html
    <footer class="py-2 bg-dark fixed-bottom">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store <span id="year"></span> </p>
        </div>
        <!-- /.container -->
    </footer>

products/templates/products/likes.html
{% load humanize %}
{% load comment_filter %}


<div class="container">
    {% if likes %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Liked goods
            <span class="badge badge-secondary badge-pill">
                        {{ likes.count }}</span>
        </h4>
        <div class="row">
        {% for like in likes %}
            <div class="col-md-3">
                <div class="card h-100">
                    <a href="">
                        <img class="card-img-top"
                             src="{{ like.product.image.url }}"
                             alt="">
                    </a>
                    <div class="card-body">
                        <a style="font-size: smaller;"
                           href="{% url 'products:product_details' like.product.id %}">{{ like.product.name }}</a>
                    </div>

                    <!-- product.liked -->
                    <div class="container pull-right">
                        {% if like.product %}
                            <div class="d-flex flex-row align-items-center text-primary">
                                <p class="small mb-0">Unlike</p>
                                <a href="">
                                    <i class="fas fa-thumbs-up mx-2 fa-xs"
                                       style="margin-top: -0.16rem;"></i>
                                </a>
                                <p class="small mb-0">{{ like.product.likes_count }}</p>
                            </div>

                        {% else %}
                            <div class="d-flex flex-row align-items-center">
                                <p class="small text-muted mb-0">Like</p>
                                <a href="">
                                    <i class="far fa-thumbs-up mx-2 fa-xs text-black"
                                       style="margin-top: -0.16rem;"></i>
                                </a>
                                <p class="small text-muted mb-0">{{ like.product.likes_count }}</p>
                            </div>
                        {% endif %}
                    </div>
                    <!-- endproduct.liked -->


                    <div class="card-footer text-center">
                        <h6>{{ like.product.price|intcomma }} usdt</h6>
                        <a style="font-size: smaller;" class="btn btn-outline-success"
                           href="{% url 'products:basket_add'  like.product.id %}">
                            Add to cart
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h6 class="mt-3 mb-3 text-center">
            You have no favorites
        </h6>
    {% endif %}

    </div>
</div>

products/templates/products/product_detail.html
{% extends 'products/_base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/css/product_detail_comment.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

    <!-- Page Content -->
    <div class="container" style="margin-top: 20px; margin-bottom: 50px">

        <div class="row">

            <div class="col-lg-3">
                {% include 'nav/categories_right_bar.html' %}
            </div>

            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div class="card mt-9 my-9">
                    <img class="card-img-top img-fluid" src="{{ object.image.url }}" alt="">
                    <div class="card-body">
                        <h3 class="card-title">{{ object.name }}</h3>
                        <h4>{{ product.price }} usdt</h4>
                        <p class="card-text">{{ product.description }}</p>
                    </div>
                </div>

                <div class="card-footer text-center">
                    <a class="btn btn-outline-success"
                       href="{% url 'products:basket_add'  product.id %}">
                        Add to cart
                    </a>
                </div>

                {% include 'products/product_detail_comment.html' %}

                {% if is_paginated %}
                    {% include 'nav/pagination.html' %}
                {% endif %}

            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    {% include 'products/footer.html' %}

{% endblock content %}

products/templates/products/product_detail_comment.html
{% load comment_filter %}
{% load static %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<section class="content-item" id="comments">
    <div class="container ">
        <div class="row">
            <div class="container">

                <div class="form-outline mb-4" id="comments">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <label for="{{ form.username.id_for_label }}" class="form-label">
                                <strong><i>{{ field.label }}</i></strong>
                            </label>
                            {{ field }}
                        {% endfor %}
                        <button class="btn btn-info" type="submit">Add comment <i class="fas fa-comments"></i></button>

                    </form>
                </div>


                <h3>{{ product.comments.count }} Comments</h3>

                {% if product.comments.count %}
                    {% for comment in product.comments.all %}
                        <div class="media" id="commentLike{{ comment.id }}">
                            <a class="pull-left" href="#"><img class="media-object"
                                                               src="{% if user.image %} {{ user.image.url }}
                                                                {% else %}
                                                                    {% static 'vendor/img/users/default_avatar.jpg' %}
                                                                {% endif %}" alt=""></a>

                            {% if comment.active %}
                                <div class="media-body">
                                    <h4 class="media-heading">@{{ comment.author }}</h4>
                                    <p>{{ comment.body }}</p>

                                    <ul class="list-unstyled list-inline media-detail pull-left" style="display: flex;">
                                        <li><i class="fa fa-calendar"></i>added {{ comment.created|timesince }} ago</li>
                                    </ul>


                                    {% if comment|is_liked_by:request.user %}
                                        <ul class="list-unstyled list-inline media-detail pull-right">
                                            <li class="">
                                                <a id="comment_like" href="{% url 'products:comment_like' comment_id=comment.id %}">Unlike
                                                    <i class="fas fa-thumbs-up mx-2 fa-xs"
                                                       style="margin-top: -0.16rem;"></i>
                                                    {{ comment.likes_count }}
                                                </a>
                                            </li>
                                        </ul>
                                    {% else %}
                                        <ul class="list-unstyled list-inline media-detail pull-right">
                                            <li class="">
                                                <a id="comment_like" href="{% url 'products:comment_like' comment_id=comment.id %}">Unlike
                                                    <i class="far fa-thumbs-up mx-2 fa-xs text-black"
                                                       style="margin-top: -0.16rem;"></i>
                                                    {{ comment.likes_count }}
                                                </a>
                                            </li>
                                        </ul>
                                    {% endif %}
                                </div>
                            {% else %}
                                <p class="text-danger"><i>Comment was disabled</i></p>
                            {% endif %}

                            <!-- is_superuser -->
                            {% if request.user.is_superuser %}
                                <a href="{% url 'products:comment_admin' comment_id=comment.id %}"
                                   class="text-decoration-none">
                                    {% if comment.active %}
                                        <button class="btn-sm btn-warning ms-auto">Disabled</button>
                                    {% else %}
                                        <button class="btn-sm btn-success ms-auto">Enabled</button>
                                    {% endif %}
                                </a>
                                <a href="{% url 'products:comment_delete_admin' comment_id=comment.id %}" class="text-decoration-none">
                                    <button class="btn-sm btn-danger ms-auto">Delete</button>
                                </a>
                            {% endif %}
                        </div>

                        <!-- COMMENT 1 - END -->
                    {% endfor %}
                {% else %}
                    <p>No comments yet.</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>

products/templates/products/products.html
{% extends 'products/_base.html' %}
{% load comment_filter %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

    <!-- Page Content -->
    <div class="container" style="margin-top: 20px; margin-bottom: 50px">
        <div class="row">
            <div class="col-lg-3">
                {% include 'nav/categories_right_bar.html' %}
            </div>
            <!-- /.col-lg-3 -->
            <div class="col-lg-9">

                <div class="row">
                    {% for product in object_list %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="{% url 'products:product_details' product.id %}">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'products:product_details' product.id %}">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price|intcomma }} usdt</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>

                                <!-- product.liked -->
                                <div class="container pull-right">
                                    {% if product|is_liked_by:request.user %}
                                        <div class="d-flex flex-row align-items-center text-primary">
                                            <p class="small mb-0">Unlike</p>
                                            <a href="{% url 'products:product_like' product_id=product.id %}">
                                                <i class="fas fa-thumbs-up mx-2 fa-xs"
                                                   style="margin-top: -0.16rem;"></i>
                                            </a>
                                            <p class="small mb-0">{{ product.likes_count }}</p>
                                        </div>

                                    {% else %}
                                        <div class="d-flex flex-row align-items-center">
                                            <p class="small text-muted mb-0">Like</p>
                                            <a href="{% url 'products:product_like' product_id=product.id %}">
                                                <i class="far fa-thumbs-up mx-2 fa-xs text-black"
                                                   style="margin-top: -0.16rem;"></i>
                                            </a>
                                            <p class="small text-muted mb-0">{{ product.likes_count }}</p>
                                        </div>
                                    {% endif %}
                                </div>
                                <!-- endproduct.liked -->

                                <div class="card-footer text-center">
                                    <a class="btn btn-outline-success"
                                       href="{% url 'products:basket_add'  product.id %}">
                                        Add to cart
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                {% if is_paginated %}
                    {% include 'nav/pagination.html' %}
                {% endif %}

            </div>
        </div>
    </div>
    <!-- /.container -->
    <!-- Footer -->
    {% include 'products/footer.html' %}
{% endblock content %}