orders/urls.py
from django.urls import path

from orders.views import (OrderCreateView,
                          SuccessTemplateView,
                          CanceledTemplateView,
                          OrderListView,
                          OrderDetailView, )

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),

    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),

    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),

]

products/urls.py
from django.urls import path

from products.views import (ProductsListView,
                            ProductDetailView,
                            basket_add, basket_remove,
                            CommentLikeView,
                            CommentLikeAdminView,
                            CommentDeleteAdminView,
                            ProductLikeView)

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('product_details/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),

    path('comment-like/<int:comment_id>', CommentLikeView.as_view(), name='comment_like'),
    path('product-like/<int:product_id>', ProductLikeView.as_view(), name='product_like'),
    path('comment-like/admin/<int:comment_id>', CommentLikeAdminView.as_view(), name='comment_admin'),
    path('comment-delete/admin/<int:comment_id>/', CommentDeleteAdminView.as_view(), name='comment_delete_admin'),

    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth.views import LogoutView

from users.views import UserLoginView, UserRegistrationView, UserProfileView, EmailVerificationView, DataGenerationView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),  # ../users/login
    path('register/', UserRegistrationView.as_view(), name='register'),  # ../users/register
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),  # ../users/profile/1
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

    path('service/', DataGenerationView.as_view(), name='service'),  # ../users/service

]

products/models.py
import stripe
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY

class ProductCategory(models.Model):
    id = models.IntegerField(primary_key=True, auto_created=False)  # disable auto increment
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')


class Product(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    id = models.IntegerField(primary_key=True, auto_created=False)  # disable auto increment
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    publish = models.DateTimeField(default=timezone.localtime)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='published')

    objects = models.Manager()
    published = PublishManager()

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ('-publish', '-created')

    def __str__(self):
        return f'Product: {self.name} | Category: {self.category.name}'

    def get_absolute_url(self):
        return reverse_lazy('products:product_details',
                            args=[self.pk, ])

    def likes_count(self):
        return self.likes.count()

    def is_liked_by(self, user):
        return self.likes.filter(user=user).exists()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='usd')
        return stripe_product_price


class ProductLike(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_likes')

    class Meta:
        unique_together = ('product', 'user')


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-updated', '-created')

    def __str__(self):
        return f'Comment by {self.author.username} - {self.body}'

    def likes_count(self):
        return self.likes.count()

    def is_liked_by(self, user):
        return self.likes.filter(user=user).exists()


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='comment_likes')

    class Meta:
        unique_together = ('comment', 'user')


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Basket for {self.user.username} | Product: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        return basket_item


"""
on_delete=models.CASCADE - delete all
on_delete=models.PROTECT - you cannot delete a category until all products belonging to this category have been deleted
on_delete=models.SET_DEFAULT, default='...' - when deleted, the default value will be set
"""

products/forms.py
from django import forms

from products.models import Comment


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={'max_length': 255,
                                                         'class': 'form-control border border-4',
                                                         'placeholder': 'Type your comment here...'}))

    class Meta:
        model = Comment
        fields = ('body',)

products/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.views.generic.base import TemplateView, View
from django.views.generic.list import ListView

from common.views import TitleMixin
from products.forms import CommentForm
from products.models import Product, ProductCategory, Basket, Comment, CommentLike, ProductLike


class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'Store'


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 9
    title = 'Store - Catalog'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()  # Product.objects.all()
        queryset = queryset.order_by('id')

        category_id = self.kwargs.get('category_id')  # None
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()

        context['categories'] = ProductCategory.objects.all()
        return context


class ProductDetailView(TitleMixin, DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    title = 'Store - Product details'
    queryset = Product.published.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)

        context['form'] = CommentForm(initial={'product': self.object})
        context['categories'] = ProductCategory.objects.all()
        return context

    @method_decorator(login_required, name='dispatch')
    def post(self, request, *args, **kwargs):
        post_comment = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = Comment(body=request.POST.get('body'),
                                  author=self.request.user,
                                  product=self.get_object())
            new_comment.save()
            return HttpResponseRedirect(f'{post_comment.get_absolute_url()}')
        return self.render_to_response({'product': post_comment, 'form': form})


class CommentLikeView(LoginRequiredMixin, View):
    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        comment_like, created = CommentLike.objects.get_or_create(comment=comment, user=request.user)
        if not created:
            comment_like.delete()
        return HttpResponseRedirect(f'{comment.product.get_absolute_url()}')


class ProductLikeView(LoginRequiredMixin, View):
    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        product_like, created = ProductLike.objects.get_or_create(product=product, user=request.user)
        if not created:
            product_like.delete()
        return HttpResponseRedirect(reverse_lazy('products:index'))


class CommentLikeAdminView(LoginRequiredMixin, View):
    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)

        if not request.user.is_superuser:
            raise PermissionDenied("You don't have permission to admin comments")

        comment.active = False if comment.active else True
        comment.save()
        return HttpResponseRedirect(f'{comment.product.get_absolute_url()}')


class CommentDeleteAdminView(LoginRequiredMixin, View):
    model = Comment

    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        if not request.user.is_superuser:
            raise PermissionDenied("You don't have permission to admin comments")
        comment.delete()
        return HttpResponseRedirect(f'{comment.product.get_absolute_url()}')


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product_id=product_id, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/nav/carousel.html
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg"
                 alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg"
                 alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg"
                 alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

products/templates/nav/categories_right_bar.html
<h1 class="my-4">Store</h1>
<div class="list-group">

    {% for category in categories %}
        <a href="{% url 'products:category' category.id %}" class="list-group-item">
            {{ category.name }}
        </a>
    {% endfor %}

</div>

products/templates/nav/nav-top-bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">


                {% if user.is_authenticated and user.is_superuser or user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:service' %}">Service <i class="fa fa-wrench"
                                                                                        aria-hidden="true"></i>
                        </a>
                    </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Catalog <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                            {% if baskets %}
                                <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">
                                    Profile
                                    <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
                                </a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">
                                Orders
                            </a></li>

                            {% if user.is_superuser or user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">
                                    Admin panel
                                </a></li>
                            {% endif %}

                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Log Out
                                </a>
                            </li>
                        </ul>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" id="log_in" href="{% url 'users:login' %}">Log In <i
                                class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

products/templates/nav/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            <a class="page-link"
               href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
               tabindex="-1" aria-disabled="true">
                Previous
            </a>
        </li>

        {% for page in paginator.page_range %}
            <li class="page-item">
                <a class="page-link" href="{% url 'products:paginator' page %}">
                    {{ page }}
                </a>
            </li>
        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
            <a class="page-link"
               href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                Next
            </a>
        </li>

    </ul>
</nav>